export const CLASSES = ['aqua', 'beast', 'bird', 'bug', 'mystic', 'plant', 'reptile', 'japanese']
export const BODY_SHAPES = ['bigyak', 'curly', 'furry', 'normal', 'spiky', 'sumo', 'wetdog'] as const
export const PARTS = [
  {
    special_genes: null,
    name: 'Zeal',
    ability_id: 'beast-eyes-02',
  },
  {
    special_genes: 'mystic',
    name: 'Calico Zeal',
    ability_id: 'beast-eyes-02',
  },
  {
    special_genes: null,
    name: 'Little Peas',
    ability_id: 'beast-eyes-04',
  },
  {
    special_genes: 'xmas',
    name: 'Snowflakes',
    ability_id: 'beast-eyes-04',
  },
  {
    special_genes: null,
    name: 'Puppy',
    ability_id: 'beast-eyes-08',
  },
  {
    special_genes: null,
    name: 'Chubby',
    ability_id: 'beast-eyes-10',
  },
  {
    special_genes: null,
    name: 'Nyan',
    ability_id: 'beast-ears-02',
  },
  {
    special_genes: 'mystic',
    name: 'Pointy Nyan',
    ability_id: 'beast-ears-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Coca',
    ability_id: 'beast-ears-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Coca Shiny',
    ability_id: 'beast-ears-02',
  },
  {
    special_genes: null,
    name: 'Nut Cracker',
    ability_id: 'beast-ears-04',
  },
  {
    special_genes: null,
    name: 'Innocent Lamb',
    ability_id: 'beast-ears-06',
  },
  {
    special_genes: 'xmas',
    name: 'Merry Lamb',
    ability_id: 'beast-ears-06',
  },
  {
    special_genes: null,
    name: 'Zen',
    ability_id: 'beast-ears-08',
  },
  {
    special_genes: null,
    name: 'Puppy',
    ability_id: 'beast-ears-10',
  },
  {
    special_genes: null,
    name: 'Belieber',
    ability_id: 'beast-ears-12',
  },
  {
    special_genes: null,
    name: 'Ronin',
    ability_id: 'beast-back-02',
  },
  {
    special_genes: 'mystic',
    name: 'Hasagi',
    ability_id: 'beast-back-02',
  },
  {
    special_genes: null,
    name: 'Hero',
    ability_id: 'beast-back-04',
  },
  {
    special_genes: null,
    name: 'Jaguar',
    ability_id: 'beast-back-06',
  },
  {
    special_genes: null,
    name: 'Risky Beast',
    ability_id: 'beast-back-08',
  },
  {
    special_genes: 'japan',
    name: 'Hamaya',
    ability_id: 'beast-back-08',
  },
  {
    special_genes: null,
    name: 'Timber',
    ability_id: 'beast-back-10',
  },
  {
    special_genes: null,
    name: 'Furball',
    ability_id: 'beast-back-12',
  },
  {
    special_genes: 'summer-2022',
    name: 'Beach Ball',
    ability_id: 'beast-back-12',
  },
  {
    special_genes: 'summer-2022',
    name: 'Beach Ball Shiny',
    ability_id: 'beast-back-12',
  },
  {
    special_genes: null,
    name: 'Little Branch',
    ability_id: 'beast-horn-02',
  },
  {
    special_genes: 'mystic',
    name: 'Winter Branch',
    ability_id: 'beast-horn-02',
  },
  {
    special_genes: null,
    name: 'Imp',
    ability_id: 'beast-horn-04',
  },
  {
    special_genes: 'japan',
    name: 'Kendama',
    ability_id: 'beast-horn-04',
  },
  {
    special_genes: null,
    name: 'Merry',
    ability_id: 'beast-horn-06',
  },
  {
    special_genes: null,
    name: 'Pocky',
    ability_id: 'beast-horn-08',
  },
  {
    special_genes: 'japan',
    name: 'Umaibo',
    ability_id: 'beast-horn-08',
  },
  {
    special_genes: null,
    name: 'Dual Blade',
    ability_id: 'beast-horn-10',
  },
  {
    special_genes: null,
    name: 'Arco',
    ability_id: 'beast-horn-12',
  },
  {
    special_genes: null,
    name: 'Cottontail',
    ability_id: 'beast-tail-02',
  },
  {
    special_genes: 'mystic',
    name: 'Sakura Cottontail',
    ability_id: 'beast-tail-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Cotton Candy',
    ability_id: 'beast-tail-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Cotton Candy Shiny',
    ability_id: 'beast-tail-02',
  },
  {
    special_genes: null,
    name: 'Rice',
    ability_id: 'beast-tail-04',
  },
  {
    special_genes: null,
    name: 'Shiba',
    ability_id: 'beast-tail-06',
  },
  {
    special_genes: null,
    name: 'Hare',
    ability_id: 'beast-tail-08',
  },
  {
    special_genes: null,
    name: 'Nut Cracker',
    ability_id: 'beast-tail-10',
  },
  {
    special_genes: null,
    name: 'Gerbil',
    ability_id: 'beast-tail-12',
  },
  {
    special_genes: null,
    name: 'Nut Cracker',
    ability_id: 'beast-mouth-02',
  },
  {
    special_genes: 'mystic',
    name: 'Skull Cracker',
    ability_id: 'beast-mouth-02',
  },
  {
    special_genes: null,
    name: 'Goda',
    ability_id: 'beast-mouth-04',
  },
  {
    special_genes: null,
    name: 'Axie Kiss',
    ability_id: 'beast-mouth-08',
  },
  {
    special_genes: null,
    name: 'Confident',
    ability_id: 'beast-mouth-10',
  },
  {
    special_genes: null,
    name: 'Mosquito',
    ability_id: 'bug-mouth-02',
  },
  {
    special_genes: 'mystic',
    name: 'Feasting Mosquito',
    ability_id: 'bug-mouth-02',
  },
  {
    special_genes: null,
    name: 'Pincer',
    ability_id: 'bug-mouth-04',
  },
  {
    special_genes: null,
    name: 'Cute Bunny',
    ability_id: 'bug-mouth-08',
  },
  {
    special_genes: 'japan',
    name: 'Kawaii',
    ability_id: 'bug-mouth-08',
  },
  {
    special_genes: null,
    name: 'Square Teeth',
    ability_id: 'bug-mouth-10',
  },
  {
    special_genes: null,
    name: 'Lagging',
    ability_id: 'bug-horn-02',
  },
  {
    special_genes: 'mystic',
    name: 'Laggingggggg',
    ability_id: 'bug-horn-02',
  },
  {
    special_genes: null,
    name: 'Antenna',
    ability_id: 'bug-horn-04',
  },
  {
    special_genes: null,
    name: 'Caterpillars',
    ability_id: 'bug-horn-06',
  },
  {
    special_genes: null,
    name: 'Pliers',
    ability_id: 'bug-horn-08',
  },
  {
    special_genes: null,
    name: 'Parasite',
    ability_id: 'bug-horn-10',
  },
  {
    special_genes: 'bionic',
    name: 'P4R451T3',
    ability_id: 'bug-horn-10',
  },
  {
    special_genes: null,
    name: 'Leaf Bug',
    ability_id: 'bug-horn-12',
  },
  {
    special_genes: null,
    name: 'Ant',
    ability_id: 'bug-tail-02',
  },
  {
    special_genes: 'mystic',
    name: 'Fire Ant',
    ability_id: 'bug-tail-02',
  },
  {
    special_genes: null,
    name: 'Twin Tail',
    ability_id: 'bug-tail-04',
  },
  {
    special_genes: null,
    name: 'Fish Snack',
    ability_id: 'bug-tail-06',
  },
  {
    special_genes: 'japan',
    name: 'Maki',
    ability_id: 'bug-tail-06',
  },
  {
    special_genes: null,
    name: 'Gravel Ant',
    ability_id: 'bug-tail-08',
  },
  {
    special_genes: null,
    name: 'Pupae',
    ability_id: 'bug-tail-10',
  },
  {
    special_genes: null,
    name: 'Thorny Caterpillar',
    ability_id: 'bug-tail-12',
  },
  {
    special_genes: null,
    name: 'Snail Shell',
    ability_id: 'bug-back-02',
  },
  {
    special_genes: 'mystic',
    name: 'Starry Shell',
    ability_id: 'bug-back-02',
  },
  {
    special_genes: null,
    name: 'Garish Worm',
    ability_id: 'bug-back-04',
  },
  {
    special_genes: 'xmas',
    name: 'Candy Canes',
    ability_id: 'bug-back-04',
  },
  {
    special_genes: null,
    name: 'Buzz Buzz',
    ability_id: 'bug-back-06',
  },
  {
    special_genes: null,
    name: 'Sandal',
    ability_id: 'bug-back-08',
  },
  {
    special_genes: null,
    name: 'Scarab',
    ability_id: 'bug-back-10',
  },
  {
    special_genes: null,
    name: 'Spiky Wing',
    ability_id: 'bug-back-12',
  },
  {
    special_genes: null,
    name: 'Larva',
    ability_id: 'bug-ears-02',
  },
  {
    special_genes: 'mystic',
    name: 'Vector',
    ability_id: 'bug-ears-02',
  },
  {
    special_genes: null,
    name: 'Beetle Spike',
    ability_id: 'bug-ears-04',
  },
  {
    special_genes: null,
    name: 'Ear Breathing',
    ability_id: 'bug-ears-06',
  },
  {
    special_genes: null,
    name: 'Leaf Bug',
    ability_id: 'bug-ears-08',
  },
  {
    special_genes: null,
    name: 'Tassels',
    ability_id: 'bug-ears-10',
  },
  {
    special_genes: null,
    name: 'Earwing',
    ability_id: 'bug-ears-12',
  },
  {
    special_genes: 'japan',
    name: 'Mon',
    ability_id: 'bug-ears-12',
  },
  {
    special_genes: null,
    name: 'Bookworm',
    ability_id: 'bug-eyes-02',
  },
  {
    special_genes: 'mystic',
    name: 'Broken Bookworm',
    ability_id: 'bug-eyes-02',
  },
  {
    special_genes: null,
    name: 'Neo',
    ability_id: 'bug-eyes-04',
  },
  {
    special_genes: 'summer-2022',
    name: 'Flower Sunglasses',
    ability_id: 'bug-eyes-04',
  },
  {
    special_genes: 'summer-2022',
    name: 'Flower Sunglasses Shiny',
    ability_id: 'bug-eyes-04',
  },
  {
    special_genes: null,
    name: 'Nerdy',
    ability_id: 'bug-eyes-08',
  },
  {
    special_genes: null,
    name: 'Kotaro?',
    ability_id: 'bug-eyes-10',
  },
  {
    special_genes: null,
    name: 'Sleepless',
    ability_id: 'aquatic-eyes-02',
  },
  {
    special_genes: 'mystic',
    name: 'Insomnia',
    ability_id: 'aquatic-eyes-02',
  },
  {
    special_genes: 'japan',
    name: 'Yen',
    ability_id: 'aquatic-eyes-02',
  },
  {
    special_genes: null,
    name: 'Clear',
    ability_id: 'aquatic-eyes-04',
  },
  {
    special_genes: null,
    name: 'Gero',
    ability_id: 'aquatic-eyes-08',
  },
  {
    special_genes: null,
    name: 'Telescope',
    ability_id: 'aquatic-eyes-10',
  },
  {
    special_genes: null,
    name: 'Lam',
    ability_id: 'aquatic-mouth-02',
  },
  {
    special_genes: 'mystic',
    name: 'Lam Handsome',
    ability_id: 'aquatic-mouth-02',
  },
  {
    special_genes: null,
    name: 'Catfish',
    ability_id: 'aquatic-mouth-04',
  },
  {
    special_genes: null,
    name: 'Risky Fish',
    ability_id: 'aquatic-mouth-08',
  },
  {
    special_genes: 'summer-2022',
    name: 'Bubble Fish',
    ability_id: 'aquatic-mouth-08',
  },
  {
    special_genes: 'summer-2022',
    name: 'Bubble Fish Shiny',
    ability_id: 'aquatic-mouth-08',
  },
  {
    special_genes: null,
    name: 'Piranha',
    ability_id: 'aquatic-mouth-10',
  },
  {
    special_genes: 'japan',
    name: 'Geisha',
    ability_id: 'aquatic-mouth-10',
  },
  {
    special_genes: null,
    name: 'Babylonia',
    ability_id: 'aquatic-horn-02',
  },
  {
    special_genes: 'mystic',
    name: 'Candy Babylonia',
    ability_id: 'aquatic-horn-02',
  },
  {
    special_genes: null,
    name: 'Teal Shell',
    ability_id: 'aquatic-horn-04',
  },
  {
    special_genes: null,
    name: 'Clamshell',
    ability_id: 'aquatic-horn-06',
  },
  {
    special_genes: null,
    name: 'Anemone',
    ability_id: 'aquatic-horn-08',
  },
  {
    special_genes: null,
    name: 'Oranda',
    ability_id: 'aquatic-horn-10',
  },
  {
    special_genes: null,
    name: 'Shoal Star',
    ability_id: 'aquatic-horn-12',
  },
  {
    special_genes: 'bionic',
    name: '5H04L-5T4R',
    ability_id: 'aquatic-horn-12',
  },
  {
    special_genes: null,
    name: 'Nimo',
    ability_id: 'aquatic-ears-02',
  },
  {
    special_genes: 'mystic',
    name: 'Red Nimo',
    ability_id: 'aquatic-ears-02',
  },
  {
    special_genes: null,
    name: 'Tiny Fan',
    ability_id: 'aquatic-ears-04',
  },
  {
    special_genes: null,
    name: 'Bubblemaker',
    ability_id: 'aquatic-ears-06',
  },
  {
    special_genes: null,
    name: 'Inkling',
    ability_id: 'aquatic-ears-08',
  },
  {
    special_genes: null,
    name: 'Gill',
    ability_id: 'aquatic-ears-10',
  },
  {
    special_genes: null,
    name: 'Seaslug',
    ability_id: 'aquatic-ears-12',
  },
  {
    special_genes: null,
    name: 'Koi',
    ability_id: 'aquatic-tail-02',
  },
  {
    special_genes: 'mystic',
    name: 'Kuro Koi',
    ability_id: 'aquatic-tail-02',
  },
  {
    special_genes: 'japan',
    name: 'Koinobori',
    ability_id: 'aquatic-tail-02',
  },
  {
    special_genes: null,
    name: 'Nimo',
    ability_id: 'aquatic-tail-04',
  },
  {
    special_genes: null,
    name: 'Tadpole',
    ability_id: 'aquatic-tail-06',
  },
  {
    special_genes: null,
    name: 'Ranchu',
    ability_id: 'aquatic-tail-08',
  },
  {
    special_genes: null,
    name: 'Navaga',
    ability_id: 'aquatic-tail-10',
  },
  {
    special_genes: null,
    name: 'Shrimp',
    ability_id: 'aquatic-tail-12',
  },
  {
    special_genes: null,
    name: 'Hermit',
    ability_id: 'aquatic-back-02',
  },
  {
    special_genes: 'mystic',
    name: 'Crystal Hermit',
    ability_id: 'aquatic-back-02',
  },
  {
    special_genes: null,
    name: 'Blue Moon',
    ability_id: 'aquatic-back-04',
  },
  {
    special_genes: null,
    name: 'Goldfish',
    ability_id: 'aquatic-back-06',
  },
  {
    special_genes: null,
    name: 'Sponge',
    ability_id: 'aquatic-back-08',
  },
  {
    special_genes: null,
    name: 'Anemone',
    ability_id: 'aquatic-back-10',
  },
  {
    special_genes: null,
    name: 'Perch',
    ability_id: 'aquatic-back-12',
  },
  {
    special_genes: null,
    name: 'Pink Cheek',
    ability_id: 'bird-ears-02',
  },
  {
    special_genes: 'mystic',
    name: 'Heart Cheek',
    ability_id: 'bird-ears-02',
  },
  {
    special_genes: null,
    name: 'Early Bird',
    ability_id: 'bird-ears-04',
  },
  {
    special_genes: null,
    name: 'Owl',
    ability_id: 'bird-ears-06',
  },
  {
    special_genes: null,
    name: 'Peace Maker',
    ability_id: 'bird-ears-08',
  },
  {
    special_genes: null,
    name: 'Curly',
    ability_id: 'bird-ears-10',
  },
  {
    special_genes: null,
    name: 'Risky Bird',
    ability_id: 'bird-ears-12',
  },
  {
    special_genes: 'japan',
    name: 'Karimata',
    ability_id: 'bird-ears-12',
  },
  {
    special_genes: null,
    name: 'Swallow',
    ability_id: 'bird-tail-02',
  },
  {
    special_genes: 'mystic',
    name: 'Snowy Swallow',
    ability_id: 'bird-tail-02',
  },
  {
    special_genes: null,
    name: 'Feather Fan',
    ability_id: 'bird-tail-04',
  },
  {
    special_genes: null,
    name: 'The Last One',
    ability_id: 'bird-tail-06',
  },
  {
    special_genes: null,
    name: 'Cloud',
    ability_id: 'bird-tail-08',
  },
  {
    special_genes: null,
    name: "Granma's Fan",
    ability_id: 'bird-tail-10',
  },
  {
    special_genes: 'japan',
    name: 'Omatsuri',
    ability_id: 'bird-tail-10',
  },
  {
    special_genes: null,
    name: 'Post Fight',
    ability_id: 'bird-tail-12',
  },
  {
    special_genes: null,
    name: 'Balloon',
    ability_id: 'bird-back-02',
  },
  {
    special_genes: 'mystic',
    name: 'Starry Balloon',
    ability_id: 'bird-back-02',
  },
  {
    special_genes: null,
    name: 'Cupid',
    ability_id: 'bird-back-04',
  },
  {
    special_genes: 'japan',
    name: 'Origami',
    ability_id: 'bird-back-04',
  },
  {
    special_genes: null,
    name: 'Raven',
    ability_id: 'bird-back-06',
  },
  {
    special_genes: null,
    name: 'Pigeon Post',
    ability_id: 'bird-back-08',
  },
  {
    special_genes: null,
    name: 'Kingfisher',
    ability_id: 'bird-back-10',
  },
  {
    special_genes: null,
    name: 'Tri Feather',
    ability_id: 'bird-back-12',
  },
  {
    special_genes: null,
    name: 'Eggshell',
    ability_id: 'bird-horn-02',
  },
  {
    special_genes: 'mystic',
    name: 'Golden Shell',
    ability_id: 'bird-horn-02',
  },
  {
    special_genes: null,
    name: 'Cuckoo',
    ability_id: 'bird-horn-04',
  },
  {
    special_genes: null,
    name: 'Trump',
    ability_id: 'bird-horn-06',
  },
  {
    special_genes: null,
    name: 'Kestrel',
    ability_id: 'bird-horn-08',
  },
  {
    special_genes: null,
    name: 'Wing Horn',
    ability_id: 'bird-horn-10',
  },
  {
    special_genes: null,
    name: 'Feather Spear',
    ability_id: 'bird-horn-12',
  },
  {
    special_genes: 'xmas',
    name: 'Spruce Spear',
    ability_id: 'bird-horn-12',
  },
  {
    special_genes: null,
    name: 'Doubletalk',
    ability_id: 'bird-mouth-02',
  },
  {
    special_genes: 'mystic',
    name: 'Mr. Doubletalk',
    ability_id: 'bird-mouth-02',
  },
  {
    special_genes: null,
    name: 'Peace Maker',
    ability_id: 'bird-mouth-04',
  },
  {
    special_genes: null,
    name: 'Hungry Bird',
    ability_id: 'bird-mouth-08',
  },
  {
    special_genes: null,
    name: 'Little Owl',
    ability_id: 'bird-mouth-10',
  },
  {
    special_genes: null,
    name: 'Mavis',
    ability_id: 'bird-eyes-02',
  },
  {
    special_genes: 'mystic',
    name: 'Sky Mavis',
    ability_id: 'bird-eyes-02',
  },
  {
    special_genes: null,
    name: 'Lucas',
    ability_id: 'bird-eyes-04',
  },
  {
    special_genes: 'xmas-2019',
    name: 'Icy Gaze',
    ability_id: 'bird-eyes-04',
  },
  {
    special_genes: null,
    name: 'Little Owl',
    ability_id: 'bird-eyes-08',
  },
  {
    special_genes: null,
    name: 'Robin',
    ability_id: 'bird-eyes-10',
  },
  {
    special_genes: null,
    name: 'Gecko',
    ability_id: 'reptile-eyes-02',
  },
  {
    special_genes: 'mystic',
    name: 'Crimson Gecko',
    ability_id: 'reptile-eyes-02',
  },
  {
    special_genes: null,
    name: 'Tricky',
    ability_id: 'reptile-eyes-04',
  },
  {
    special_genes: null,
    name: 'Scar',
    ability_id: 'reptile-eyes-08',
  },
  {
    special_genes: 'japan',
    name: 'Dokuganryu',
    ability_id: 'reptile-eyes-08',
  },
  {
    special_genes: null,
    name: 'Topaz',
    ability_id: 'reptile-eyes-10',
  },
  {
    special_genes: 'japan',
    name: 'Kabuki',
    ability_id: 'reptile-eyes-10',
  },
  {
    special_genes: null,
    name: 'Toothless Bite',
    ability_id: 'reptile-mouth-02',
  },
  {
    special_genes: 'mystic',
    name: 'Venom Bite',
    ability_id: 'reptile-mouth-02',
  },
  {
    special_genes: null,
    name: 'Kotaro',
    ability_id: 'reptile-mouth-04',
  },
  {
    special_genes: null,
    name: 'Razor Bite',
    ability_id: 'reptile-mouth-08',
  },
  {
    special_genes: null,
    name: 'Tiny Turtle',
    ability_id: 'reptile-mouth-10',
  },
  {
    special_genes: 'japan',
    name: 'Dango',
    ability_id: 'reptile-mouth-10',
  },
  {
    special_genes: 'xmas-2019',
    name: 'Tiny Carrot',
    ability_id: 'reptile-mouth-10',
  },
  {
    special_genes: null,
    name: 'Pogona',
    ability_id: 'reptile-ears-02',
  },
  {
    special_genes: 'mystic',
    name: 'Deadly Pogona',
    ability_id: 'reptile-ears-02',
  },
  {
    special_genes: null,
    name: 'Friezard',
    ability_id: 'reptile-ears-04',
  },
  {
    special_genes: null,
    name: 'Curved Spine',
    ability_id: 'reptile-ears-06',
  },
  {
    special_genes: null,
    name: 'Small Frill',
    ability_id: 'reptile-ears-08',
  },
  {
    special_genes: null,
    name: 'Swirl',
    ability_id: 'reptile-ears-10',
  },
  {
    special_genes: null,
    name: 'Sidebarb',
    ability_id: 'reptile-ears-12',
  },
  {
    special_genes: null,
    name: 'Bone Sail',
    ability_id: 'reptile-back-02',
  },
  {
    special_genes: 'mystic',
    name: 'Rugged Sail',
    ability_id: 'reptile-back-02',
  },
  {
    special_genes: null,
    name: 'Tri Spikes',
    ability_id: 'reptile-back-04',
  },
  {
    special_genes: null,
    name: 'Green Thorns',
    ability_id: 'reptile-back-06',
  },
  {
    special_genes: null,
    name: 'Indian Star',
    ability_id: 'reptile-back-08',
  },
  {
    special_genes: 'bionic',
    name: '1ND14N-5T4R',
    ability_id: 'reptile-back-08',
  },
  {
    special_genes: 'xmas-2019',
    name: 'Frozen Bucket',
    ability_id: 'reptile-back-08',
  },
  {
    special_genes: null,
    name: 'Red Ear',
    ability_id: 'reptile-back-10',
  },
  {
    special_genes: 'summer-2022',
    name: 'Turtle Buoy',
    ability_id: 'reptile-back-10',
  },
  {
    special_genes: 'summer-2022',
    name: 'Turtle Buoy Shiny',
    ability_id: 'reptile-back-10',
  },
  {
    special_genes: null,
    name: 'Croc',
    ability_id: 'reptile-back-12',
  },
  {
    special_genes: null,
    name: 'Wall Gecko',
    ability_id: 'reptile-tail-02',
  },
  {
    special_genes: 'mystic',
    name: 'Escaped Gecko',
    ability_id: 'reptile-tail-02',
  },
  {
    special_genes: null,
    name: 'Iguana',
    ability_id: 'reptile-tail-04',
  },
  {
    special_genes: null,
    name: 'Tiny Dino',
    ability_id: 'reptile-tail-06',
  },
  {
    special_genes: 'xmas-2019',
    name: 'Fir Trunk',
    ability_id: 'reptile-tail-06',
  },
  {
    special_genes: null,
    name: 'Snake Jar',
    ability_id: 'reptile-tail-08',
  },
  {
    special_genes: 'xmas',
    name: 'December Surprise',
    ability_id: 'reptile-tail-08',
  },
  {
    special_genes: null,
    name: 'Gila',
    ability_id: 'reptile-tail-10',
  },
  {
    special_genes: null,
    name: 'Grass Snake',
    ability_id: 'reptile-tail-12',
  },
  {
    special_genes: null,
    name: 'Unko',
    ability_id: 'reptile-horn-02',
  },
  {
    special_genes: 'mystic',
    name: 'Pinku Unko',
    ability_id: 'reptile-horn-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Watermelon Ice Cream',
    ability_id: 'reptile-horn-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Strawberry Ice Cream',
    ability_id: 'reptile-horn-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Vanilla Ice Cream',
    ability_id: 'reptile-horn-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Watermelon Ice Cream Shiny',
    ability_id: 'reptile-horn-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Strawberry Ice Cream Shiny',
    ability_id: 'reptile-horn-02',
  },
  {
    special_genes: 'summer-2022',
    name: 'Vanilla Ice Cream Shiny',
    ability_id: 'reptile-horn-02',
  },
  {
    special_genes: null,
    name: 'Scaly Spear',
    ability_id: 'reptile-horn-04',
  },
  {
    special_genes: null,
    name: 'Cerastes',
    ability_id: 'reptile-horn-06',
  },
  {
    special_genes: null,
    name: 'Scaly Spoon',
    ability_id: 'reptile-horn-08',
  },
  {
    special_genes: null,
    name: 'Incisor',
    ability_id: 'reptile-horn-10',
  },
  {
    special_genes: null,
    name: 'Bumpy',
    ability_id: 'reptile-horn-12',
  },
  {
    special_genes: null,
    name: 'Carrot',
    ability_id: 'plant-tail-02',
  },
  {
    special_genes: 'mystic',
    name: 'Namek Carrot',
    ability_id: 'plant-tail-02',
  },
  {
    special_genes: null,
    name: 'Cattail',
    ability_id: 'plant-tail-04',
  },
  {
    special_genes: null,
    name: 'Hatsune',
    ability_id: 'plant-tail-06',
  },
  {
    special_genes: null,
    name: 'Yam',
    ability_id: 'plant-tail-08',
  },
  {
    special_genes: null,
    name: 'Potato Leaf',
    ability_id: 'plant-tail-10',
  },
  {
    special_genes: null,
    name: 'Hot Butt',
    ability_id: 'plant-tail-12',
  },
  {
    special_genes: null,
    name: 'Serious',
    ability_id: 'plant-mouth-02',
  },
  {
    special_genes: 'mystic',
    name: 'Humorless',
    ability_id: 'plant-mouth-02',
  },
  {
    special_genes: null,
    name: 'Zigzag',
    ability_id: 'plant-mouth-04',
  },
  {
    special_genes: 'xmas',
    name: 'Rudolph',
    ability_id: 'plant-mouth-04',
  },
  {
    special_genes: null,
    name: 'Herbivore',
    ability_id: 'plant-mouth-08',
  },
  {
    special_genes: null,
    name: 'Silence Whisper',
    ability_id: 'plant-mouth-10',
  },
  {
    special_genes: null,
    name: 'Papi',
    ability_id: 'plant-eyes-02',
  },
  {
    special_genes: 'mystic',
    name: 'Dreamy Papi',
    ability_id: 'plant-eyes-02',
  },
  {
    special_genes: null,
    name: 'Confused',
    ability_id: 'plant-eyes-04',
  },
  {
    special_genes: null,
    name: 'Cucumber Slice',
    ability_id: 'plant-eyes-08',
  },
  {
    special_genes: null,
    name: 'Blossom',
    ability_id: 'plant-eyes-10',
  },
  {
    special_genes: null,
    name: 'Leafy',
    ability_id: 'plant-ears-02',
  },
  {
    special_genes: 'mystic',
    name: 'The Last Leaf',
    ability_id: 'plant-ears-02',
  },
  {
    special_genes: null,
    name: 'Clover',
    ability_id: 'plant-ears-04',
  },
  {
    special_genes: null,
    name: 'Rosa',
    ability_id: 'plant-ears-06',
  },
  {
    special_genes: null,
    name: 'Sakura',
    ability_id: 'plant-ears-08',
  },
  {
    special_genes: 'japan',
    name: 'Maiko',
    ability_id: 'plant-ears-08',
  },
  {
    special_genes: null,
    name: 'Hollow',
    ability_id: 'plant-ears-10',
  },
  {
    special_genes: 'xmas-2019',
    name: 'Pinecones',
    ability_id: 'plant-ears-10',
  },
  {
    special_genes: null,
    name: 'Lotus',
    ability_id: 'plant-ears-12',
  },
  {
    special_genes: null,
    name: 'Turnip',
    ability_id: 'plant-back-02',
  },
  {
    special_genes: 'mystic',
    name: 'Pink Turnip',
    ability_id: 'plant-back-02',
  },
  {
    special_genes: null,
    name: 'Shiitake',
    ability_id: 'plant-back-04',
  },
  {
    special_genes: 'japan',
    name: 'Yakitori',
    ability_id: 'plant-back-04',
  },
  {
    special_genes: null,
    name: 'Bidens',
    ability_id: 'plant-back-06',
  },
  {
    special_genes: null,
    name: 'Watering Can',
    ability_id: 'plant-back-08',
  },
  {
    special_genes: null,
    name: 'Mint',
    ability_id: 'plant-back-10',
  },
  {
    special_genes: null,
    name: 'Pumpkin',
    ability_id: 'plant-back-12',
  },
  {
    special_genes: null,
    name: 'Bamboo Shoot',
    ability_id: 'plant-horn-02',
  },
  {
    special_genes: 'mystic',
    name: 'Golden Bamboo Shoot',
    ability_id: 'plant-horn-02',
  },
  {
    special_genes: null,
    name: 'Beech',
    ability_id: 'plant-horn-04',
  },
  {
    special_genes: 'japan',
    name: 'Yorishiro',
    ability_id: 'plant-horn-04',
  },
  {
    special_genes: null,
    name: 'Rose Bud',
    ability_id: 'plant-horn-06',
  },
  {
    special_genes: null,
    name: 'Strawberry Shortcake',
    ability_id: 'plant-horn-08',
  },
  {
    special_genes: null,
    name: 'Cactus',
    ability_id: 'plant-horn-10',
  },
  {
    special_genes: 'xmas-2019',
    name: "Santa's Gift",
    ability_id: 'plant-horn-10',
  },
  {
    special_genes: null,
    name: 'Watermelon',
    ability_id: 'plant-horn-12',
  },
]

export const COLORS = [
  {
    index: 0,
    key: 'beast-00',
    skin: 0,
    class: 'beast',
    color_value: 0,
    primary1: 'fdfcf2',
    shaded1: 'ddd6ae',
    primary2: 'af8c56',
    shaded2: '7d542c',
    line: 'fa9000',
    partColorShift: '0000000',
  },
  {
    index: 1,
    key: 'beast-01',
    skin: 0,
    class: 'beast',
    color_value: 1,
    primary1: '544f44',
    shaded1: '3f392f',
    primary2: 'edd8b8',
    shaded2: 'c19872',
    line: '6b4f24',
    partColorShift: '0000000',
  },
  {
    index: 2,
    key: 'beast-02',
    skin: 0,
    class: 'beast',
    color_value: 2,
    primary1: 'ffd500',
    shaded1: 'f8a500',
    primary2: 'fffeda',
    shaded2: 'f3d459',
    line: 'fa9000',
    partColorShift: '0000000',
  },
  {
    index: 3,
    key: 'beast-03',
    skin: 0,
    class: 'beast',
    color_value: 3,
    primary1: 'fdb014',
    shaded1: 'eb7e00',
    primary2: 'fef0a3',
    shaded2: 'f0bb53',
    line: 'ff8000',
    partColorShift: '0000000',
  },
  {
    index: 4,
    key: 'beast-04',
    skin: 0,
    class: 'beast',
    color_value: 4,
    primary1: 'f5a037',
    shaded1: 'd98035',
    primary2: 'fde5b6',
    shaded2: 'ecb686',
    line: 'ff8000',
    partColorShift: '0000000',
  },
  {
    index: 5,
    key: 'beast-06',
    skin: 0,
    class: 'beast',
    color_value: 6,
    primary1: '427cad',
    shaded1: '1362a2',
    primary2: 'ffcd63',
    shaded2: 'dd9200',
    line: '0063af',
    partColorShift: '0000000',
  },
  {
    index: 6,
    key: 'plant-00',
    skin: 0,
    class: 'plant',
    color_value: 0,
    primary1: 'fefdf1',
    shaded1: 'd2d9b3',
    primary2: '98984a',
    shaded2: '606718',
    line: 'a0be00',
    partColorShift: '0000000',
  },
  {
    index: 7,
    key: 'plant-01',
    skin: 0,
    class: 'plant',
    color_value: 1,
    primary1: '4e523e',
    shaded1: '414630',
    primary2: 'efe5a7',
    shaded2: 'b0a657',
    line: '415800',
    partColorShift: '0000000',
  },
  {
    index: 8,
    key: 'plant-02',
    skin: 0,
    class: 'plant',
    color_value: 2,
    primary1: 'afdb1b',
    shaded1: '75ba00',
    primary2: 'e3efdb',
    shaded2: 'aebd44',
    line: '70ce00',
    partColorShift: '0000000',
  },
  {
    index: 9,
    key: 'plant-03',
    skin: 0,
    class: 'plant',
    color_value: 3,
    primary1: 'decd00',
    shaded1: 'a89b00',
    primary2: 'f3eaba',
    shaded2: 'c3b641',
    line: 'aab900',
    partColorShift: '0000000',
  },
  {
    index: 10,
    key: 'plant-04',
    skin: 0,
    class: 'plant',
    color_value: 4,
    primary1: '99ff73',
    shaded1: '6ada00',
    primary2: 'fbfdf1',
    shaded2: 'b1e180',
    line: '10dd00',
    partColorShift: '0000000',
  },
  {
    index: 11,
    key: 'aquatic-00',
    skin: 0,
    class: 'aquatic',
    color_value: 0,
    primary1: 'f4fff4',
    shaded1: 'b5e1cc',
    primary2: '3ca1d9',
    shaded2: '1170aa',
    line: '00bbff',
    partColorShift: '0000000',
  },
  {
    index: 12,
    key: 'aquatic-01',
    skin: 0,
    class: 'aquatic',
    color_value: 1,
    primary1: '4d545e',
    shaded1: '3d434b',
    primary2: 'a9ead5',
    shaded2: '44b2b2',
    line: '395089',
    partColorShift: '0000000',
  },
  {
    index: 13,
    key: 'aquatic-02',
    skin: 0,
    class: 'aquatic',
    color_value: 2,
    primary1: '00f1d2',
    shaded1: '00c6cc',
    primary2: 'befedb',
    shaded2: '4ddcc6',
    line: '00d4f0',
    partColorShift: '0000000',
  },
  {
    index: 14,
    key: 'aquatic-03',
    skin: 0,
    class: 'aquatic',
    color_value: 3,
    primary1: '00dff3',
    shaded1: '00add6',
    primary2: 'bffef4',
    shaded2: '59d7da',
    line: '00d4f0',
    partColorShift: '0000000',
  },
  {
    index: 15,
    key: 'aquatic-04',
    skin: 0,
    class: 'aquatic',
    color_value: 4,
    primary1: '00b8ff',
    shaded1: '008de7',
    primary2: 'c9eeff',
    shaded2: '00cef7',
    line: '00bbff',
    partColorShift: '0000000',
  },
  {
    index: 16,
    key: 'aquatic-06',
    skin: 0,
    class: 'aquatic',
    color_value: 6,
    primary1: 'e12f64',
    shaded1: 'bc0056',
    primary2: '62ffe2',
    shaded2: '00c2c7',
    line: 'e50060',
    partColorShift: '0000000',
  },
  {
    index: 17,
    key: 'bug-00',
    skin: 0,
    class: 'bug',
    color_value: 0,
    primary1: 'fffaf5',
    shaded1: 'efccbb',
    primary2: 'e22737',
    shaded2: '970940',
    line: 'de0000',
    partColorShift: '0000000',
  },
  {
    index: 18,
    key: 'bug-01',
    skin: 0,
    class: 'bug',
    color_value: 1,
    primary1: '553b39',
    shaded1: '432e30',
    primary2: 'ffe7e2',
    shaded2: 'ff9e94',
    line: '6f241e',
    partColorShift: '0000000',
  },
  {
    index: 19,
    key: 'bug-02',
    skin: 0,
    class: 'bug',
    color_value: 2,
    primary1: 'ff606c',
    shaded1: 'f2213e',
    primary2: 'fff4f9',
    shaded2: 'ffa9af',
    line: 'de0000',
    partColorShift: '0000000',
  },
  {
    index: 20,
    key: 'bug-03',
    skin: 0,
    class: 'bug',
    color_value: 3,
    primary1: 'ff433e',
    shaded1: 'dc1244',
    primary2: 'ffdcce',
    shaded2: 'ffa587',
    line: 'de0000',
    partColorShift: '0000000',
  },
  {
    index: 21,
    key: 'bug-04',
    skin: 0,
    class: 'bug',
    color_value: 4,
    primary1: 'df2e54',
    shaded1: 'b4154f',
    primary2: 'ffd8d6',
    shaded2: 'ff9f96',
    line: 'de0000',
    partColorShift: '0000000',
  },
  {
    index: 22,
    key: 'bird-00',
    skin: 0,
    class: 'bird',
    color_value: 0,
    primary1: 'fff7ff',
    shaded1: 'f6c1e3',
    primary2: 'fa59a0',
    shaded2: 'cc2e6f',
    line: 'e40086',
    partColorShift: '0000000',
  },
  {
    index: 23,
    key: 'bird-01',
    skin: 0,
    class: 'bird',
    color_value: 1,
    primary1: '583c44',
    shaded1: '4a303a',
    primary2: 'fec3dd',
    shaded2: 'e37aa5',
    line: '6d2d5e',
    partColorShift: '0000000',
  },
  {
    index: 24,
    key: 'bird-02',
    skin: 0,
    class: 'bird',
    color_value: 2,
    primary1: 'ff99b0',
    shaded1: 'f6749d',
    primary2: 'ffd8f3',
    shaded2: 'f89dcc',
    line: 'e40086',
    partColorShift: '0000000',
  },
  {
    index: 25,
    key: 'bird-03',
    skin: 0,
    class: 'bird',
    color_value: 3,
    primary1: 'ffafc1',
    shaded1: 'f78299',
    primary2: 'ffe0e7',
    shaded2: 'ffa5b3',
    line: 'e40086',
    partColorShift: '0000000',
  },
  {
    index: 26,
    key: 'bird-04',
    skin: 0,
    class: 'bird',
    color_value: 4,
    primary1: 'ff78b4',
    shaded1: 'f358a1',
    primary2: 'ffedff',
    shaded2: 'ffb0e1',
    line: 'e40086',
    partColorShift: '0000000',
  },
  {
    index: 27,
    key: 'reptile-00',
    skin: 0,
    class: 'reptile',
    color_value: 0,
    primary1: 'fff7ff',
    shaded1: 'e2c8ef',
    primary2: 'bb68ce',
    shaded2: '834296',
    line: '9f00ef',
    partColorShift: '0000000',
  },
  {
    index: 28,
    key: 'reptile-01',
    skin: 0,
    class: 'reptile',
    color_value: 1,
    primary1: '5e436d',
    shaded1: '533759',
    primary2: 'f4cdfe',
    shaded2: 'd38ed3',
    line: '733ba0',
    partColorShift: '0000000',
  },
  {
    index: 29,
    key: 'reptile-02',
    skin: 0,
    class: 'reptile',
    color_value: 2,
    primary1: 'c569cf',
    shaded1: 'a754b4',
    primary2: 'ffd2fe',
    shaded2: 'f78ee2',
    line: 'd900d0',
    partColorShift: '0000000',
  },
  {
    index: 30,
    key: 'reptile-03',
    skin: 0,
    class: 'reptile',
    color_value: 3,
    primary1: '9967fb',
    shaded1: '7d4ce7',
    primary2: 'dac3ff',
    shaded2: 'a988ff',
    line: '8d24ff',
    partColorShift: '0000000',
  },
  {
    index: 31,
    key: 'reptile-04',
    skin: 0,
    class: 'reptile',
    color_value: 4,
    primary1: 'f8bbff',
    shaded1: 'e28ddd',
    primary2: 'fff1fe',
    shaded2: 'fbaee9',
    line: 'e90fe7',
    partColorShift: '0000000',
  },
  {
    index: 32,
    key: 'reptile-06',
    skin: 0,
    class: 'reptile',
    color_value: 6,
    primary1: '00c15f',
    shaded1: '009291',
    primary2: 'f4aaff',
    shaded2: 'c56fff',
    line: '008cd1',
    partColorShift: '0000000',
  },
  {
    index: 33,
    key: 'dawn-00',
    skin: 0,
    class: 'dawn',
    color_value: 0,
    primary1: 'fcfbf2',
    shaded1: 'aee5c4',
    primary2: 'd4f8d0',
    shaded2: '7ddbcf',
    line: '7d7300',
    partColorShift: '0000000',
  },
  {
    index: 34,
    key: 'dawn-01',
    skin: 0,
    class: 'dawn',
    color_value: 1,
    primary1: '594026',
    shaded1: '452e1f',
    primary2: 'fede29',
    shaded2: 'e88e00',
    line: '702f00',
    partColorShift: '0000000',
  },
  {
    index: 35,
    key: 'dawn-02',
    skin: 0,
    class: 'dawn',
    color_value: 2,
    primary1: 'bbbaff',
    shaded1: 'ba96ff',
    primary2: 'eaf8ff',
    shaded2: 'a7b6ff',
    line: '9933ff',
    partColorShift: '0000000',
  },
  {
    index: 36,
    key: 'dawn-03',
    skin: 0,
    class: 'dawn',
    color_value: 3,
    primary1: 'ffff8d',
    shaded1: 'ffd200',
    primary2: 'feffe3',
    shaded2: '88e9d7',
    line: 'e66c00',
    partColorShift: '0000000',
  },
  {
    index: 37,
    key: 'dawn-04',
    skin: 0,
    class: 'dawn',
    color_value: 4,
    primary1: 'a5ffff',
    shaded1: 'f6baff',
    primary2: 'ffffff',
    shaded2: 'ffb2d9',
    line: 'a527ff',
    partColorShift: '0000000',
  },
  {
    index: 38,
    key: 'dusk-00',
    skin: 0,
    class: 'dusk',
    color_value: 0,
    primary1: 'f4fefb',
    shaded1: '93ebd1',
    primary2: 'feffff',
    shaded2: 'a4e7e0',
    line: '007c78',
    partColorShift: '0000000',
  },
  {
    index: 39,
    key: 'dusk-01',
    skin: 0,
    class: 'dusk',
    color_value: 1,
    primary1: '1d4d4f',
    shaded1: '1b3b47',
    primary2: 'd0fec0',
    shaded2: '00dfc6',
    line: '00445b',
    partColorShift: '0000000',
  },
  {
    index: 40,
    key: 'dusk-02',
    skin: 0,
    class: 'dusk',
    color_value: 2,
    primary1: '0097a0',
    shaded1: '006e95',
    primary2: 'abffac',
    shaded2: '00e180',
    line: '0099bc',
    partColorShift: '0000000',
  },
  {
    index: 41,
    key: 'dusk-03',
    skin: 0,
    class: 'dusk',
    color_value: 3,
    primary1: '007181',
    shaded1: '005372',
    primary2: '62feda',
    shaded2: '00dabb',
    line: '006e99',
    partColorShift: '0000000',
  },
  {
    index: 42,
    key: 'dusk-04',
    skin: 0,
    class: 'dusk',
    color_value: 4,
    primary1: '00aeb7',
    shaded1: '0081a5',
    primary2: 'a4ffcb',
    shaded2: '00dfa6',
    line: '009be5',
    partColorShift: '0000000',
  },
  {
    index: 43,
    key: 'mech-00',
    skin: 0,
    class: 'mech',
    color_value: 0,
    primary1: 'f6fbff',
    shaded1: 'c6cfcf',
    primary2: '929292',
    shaded2: '5f5f5f',
    line: '838383',
    partColorShift: '0000000',
  },
  {
    index: 44,
    key: 'mech-01',
    skin: 0,
    class: 'mech',
    color_value: 1,
    primary1: '505050',
    shaded1: '434343',
    primary2: 'e5e5e5',
    shaded2: 'a6a6a6',
    line: '474747',
    partColorShift: '0000000',
  },
  {
    index: 45,
    key: 'mech-02',
    skin: 0,
    class: 'mech',
    color_value: 2,
    primary1: 'ced5d7',
    shaded1: '97aeb0',
    primary2: 'f1fdf0',
    shaded2: '9bcfca',
    line: '008eb0',
    partColorShift: '0000000',
  },
  {
    index: 46,
    key: 'mech-03',
    skin: 0,
    class: 'mech',
    color_value: 3,
    primary1: 'ad6d3f',
    shaded1: '994b3b',
    primary2: '9ae6cb',
    shaded2: '56a6cd',
    line: 'cb4800',
    partColorShift: '0000000',
  },
  {
    index: 47,
    key: 'mech-04',
    skin: 0,
    class: 'mech',
    color_value: 4,
    primary1: '8c8e9e',
    shaded1: '706a8c',
    primary2: 'ebe7de',
    shaded2: 'bda395',
    line: '595fc2',
    partColorShift: '0000000',
  },
  {
    index: 48,
    key: 'body-frosty',
    skin: 1,
    class: 'any',
    color_value: -1,
    primary1: 'f3fefe',
    shaded1: '6acad7',
    primary2: 'f3fefe',
    shaded2: '6acad7',
    line: '0097d2',
    partColorShift: '0000000',
  },
  {
    index: 49,
    key: 'beast-summer',
    skin: 2,
    class: 'beast',
    color_value: -1,
    primary1: 'fe9701',
    shaded1: 'df5414',
    primary2: 'fff6ec',
    shaded2: 'dec8b7',
    line: 'ff8000',
    partColorShift: '0000011',
  },
  {
    index: 50,
    key: 'plant-summer',
    skin: 2,
    class: 'plant',
    color_value: -1,
    primary1: '67e92f',
    shaded1: '019d74',
    primary2: 'f6fff7',
    shaded2: 'bcd5cf',
    line: '10dd00',
    partColorShift: '0000011',
  },
  {
    index: 51,
    key: 'aquatic-summer',
    skin: 2,
    class: 'aquatic',
    color_value: -1,
    primary1: '00c5d0',
    shaded1: '0081c2',
    primary2: 'f5fffd',
    shaded2: 'c2cedd',
    line: '00d4f0',
    partColorShift: '0000011',
  },
  {
    index: 52,
    key: 'bug-summer',
    skin: 2,
    class: 'bug',
    color_value: -1,
    primary1: 'ff4363',
    shaded1: 'd20539',
    primary2: 'fffdff',
    shaded2: 'e5c1c8',
    line: 'de0000',
    partColorShift: '0000011',
  },
  {
    index: 53,
    key: 'bird-summer',
    skin: 2,
    class: 'bird',
    color_value: -1,
    primary1: 'ff78bb',
    shaded1: 'e63c8b',
    primary2: 'fffdff',
    shaded2: 'e4bfd8',
    line: 'e40086',
    partColorShift: '0000011',
  },
  {
    index: 54,
    key: 'reptile-summer',
    skin: 2,
    class: 'reptile',
    color_value: -1,
    primary1: 'e173ff',
    shaded1: 'a349f9',
    primary2: 'fefeff',
    shaded2: 'd9c1e7',
    line: '8d24ff',
    partColorShift: '0000011',
  },
  {
    index: 55,
    key: 'dawn-summer',
    skin: 2,
    class: 'dawn',
    color_value: -1,
    primary1: 'ffda00',
    shaded1: 'fff527',
    primary2: 'f8fdea',
    shaded2: 'e5e4c6',
    line: 'e66c00',
    partColorShift: '0000011',
  },
  {
    index: 56,
    key: 'mech-summer',
    skin: 2,
    class: 'mech',
    color_value: -1,
    primary1: 'c7d7e9',
    shaded1: 'b0e4ff',
    primary2: 'fefeff',
    shaded2: 'dfe9ec',
    line: '008eb0',
    partColorShift: '0000011',
  },
  {
    index: 57,
    key: 'dusk-summer',
    skin: 2,
    class: 'dusk',
    color_value: -1,
    primary1: '474b84',
    shaded1: '4e50dd',
    primary2: 'fefeff',
    shaded2: 'e4e6f2',
    line: '006e99',
    partColorShift: '0000011',
  },
]

export const PART_POSITION: Record<string, { [key: string]: Array<string> }> = {
  back: {
    aqua_02: ['m'],
    aqua_04: ['m'],
    aqua_06: ['m'],
    aqua_08: ['m'],
    aqua_10: ['m'],
    aqua_12: ['m'],
    beast_02: ['m'],
    beast_04: ['m'],
    beast_06: ['m'],
    beast_08: ['m'],
    beast_10: ['m'],
    beast_12: ['m'],
    bird_02: ['m'],
    bird_04: ['l', 'r'],
    bird_06: ['l', 'r'],
    bird_08: ['m'],
    bird_10: ['l', 'r'],
    bird_12: ['m'],
    bug_02: ['m'],
    bug_04: ['m'],
    bug_06: ['l', 'r'],
    bug_08: ['m'],
    bug_10: ['m'],
    bug_12: ['m'],
    japanese_02: ['l', 'r'],
    japanese_04: ['m'],
    japanese_06: ['m'],
    mystic_02: ['m'],
    mystic_04: ['m'],
    mystic_06: ['m'],
    mystic_08: ['m'],
    mystic_10: ['m'],
    mystic_12: ['m'],
    plant_02: ['m'],
    plant_06: ['m'],
    plant_04: ['m'],
    plant_08: ['m'],
    plant_10: ['m'],
    plant_12: ['m'],
    reptile_02: ['m'],
    reptile_04: ['m'],
    reptile_06: ['l', 'r'],
    reptile_08: ['m'],
    reptile_10: ['m'],
    reptile_12: ['l', 'r'],
  },
  ear: {
    aqua_02: ['l', 'r'],
    aqua_04: ['l', 'r'],
    aqua_06: ['l', 'r'],
    aqua_08: ['l', 'r'],
    aqua_10: ['l', 'r'],
    aqua_12: ['l', 'r'],
    beast_02: ['l', 'r'],
    beast_04: ['l', 'r'],
    beast_06: ['l', 'r'],
    beast_08: ['l', 'r'],
    beast_10: ['l', 'r'],
    beast_12: ['l', 'r'],
    bird_02: ['l', 'r'],
    bird_04: ['l', 'r'],
    bird_06: ['l', 'r'],
    bird_08: ['l', 'r'],
    bird_10: ['l', 'r'],
    bird_12: ['l', 'r'],
    bug_02: ['l', 'r'],
    bug_04: ['l', 'r'],
    bug_06: ['l', 'r'],
    bug_08: ['l', 'r'],
    bug_10: ['l', 'r'],
    bug_12: ['l', 'r'],
    japanese_02: ['l', 'r'],
    japanese_04: ['l', 'r'],
    japanese_06: ['l', 'r'],
    mystic_02: ['l', 'r'],
    mystic_04: ['l', 'r'],
    mystic_06: ['l', 'r'],
    mystic_08: ['l', 'r'],
    mystic_10: ['l', 'r'],
    mystic_12: ['l', 'r'],
    plant_02: ['l', 'r'],
    plant_04: ['l', 'r'],
    plant_06: ['l', 'r'],
    plant_08: ['l', 'r'],
    plant_10: ['l', 'r'],
    plant_12: ['l', 'r'],
    reptile_02: ['l', 'r'],
    reptile_04: ['l', 'r'],
    reptile_06: ['l', 'r'],
    reptile_08: ['l', 'r'],
    reptile_10: ['l', 'r'],
    reptile_12: ['l', 'r'],
  },
  eye: {
    aqua_02: ['m'],
    aqua_04: ['m'],
    aqua_06: ['m'],
    aqua_08: ['m'],
    aqua_10: ['m'],
    aqua_12: ['m'],
    beast_02: ['m'],
    beast_04: ['m'],
    beast_06: ['m'],
    beast_08: ['m'],
    beast_10: ['m'],
    beast_12: ['m'],
    bird_02: ['m'],
    bird_04: ['m'],
    bird_06: ['m'],
    bird_08: ['m'],
    bird_10: ['m'],
    bird_12: ['m'],
    bug_02: ['m'],
    bug_04: ['m'],
    bug_06: ['m'],
    bug_08: ['m'],
    bug_10: ['m'],
    bug_12: ['m'],
    mystic_02: ['m'],
    mystic_04: ['m'],
    mystic_06: ['m'],
    mystic_08: ['m'],
    mystic_10: ['m'],
    mystic_12: ['m'],
    plant_02: ['m'],
    plant_04: ['m'],
    plant_06: ['m'],
    plant_08: ['m'],
    plant_10: ['m'],
    plant_12: ['m'],
    reptile_02: ['m'],
    reptile_04: ['m'],
    reptile_06: ['m'],
    reptile_08: ['m'],
    reptile_10: ['m'],
    reptile_12: ['m'],
  },
  horn: {
    aqua_02: ['l', 'r'],
    aqua_04: ['t'],
    aqua_06: ['t'],
    aqua_08: ['t'],
    aqua_10: ['t'],
    aqua_12: ['t'],
    beast_02: ['l', 'r'],
    beast_04: ['l', 'r', 't'],
    beast_06: ['l', 'r'],
    beast_08: ['l', 'r'],
    beast_10: ['l', 'r'],
    beast_12: ['l', 'r'],
    bird_02: ['t'],
    bird_04: ['t'],
    bird_06: ['t'],
    bird_08: ['t'],
    bird_10: ['l', 'r'],
    bird_12: ['t'],
    bug_02: ['l', 'r'],
    bug_04: ['l', 'r'],
    bug_06: ['l', 'r'],
    bug_08: ['t'],
    bug_10: ['t'],
    bug_12: ['l', 'r'],
    japanese_02: ['t'],
    japanese_04: ['l', 'r'],
    japanese_06: ['t'],
    mystic_02: ['l', 'r'],
    mystic_04: ['l', 'r'],
    mystic_06: ['t'],
    mystic_08: ['t'],
    mystic_10: ['l', 'r'],
    mystic_12: ['t'],
    plant_02: ['t'],
    plant_04: ['t'],
    plant_06: ['t'],
    plant_08: ['t'],
    plant_10: ['t'],
    plant_12: ['t'],
    reptile_02: ['t'],
    reptile_04: ['t'],
    reptile_06: ['l', 'r'],
    reptile_08: ['l', 'r'],
    reptile_10: ['l', 'r'],
    reptile_12: ['l', 'r'],
  },
  tail: {
    aqua_02: ['m'],
    aqua_04: ['m'],
    aqua_06: ['m'],
    aqua_08: ['m'],
    aqua_10: ['m'],
    aqua_12: ['m'],
    beast_02: ['m'],
    beast_04: ['m'],
    beast_06: ['m'],
    beast_08: ['m'],
    beast_10: ['m'],
    beast_12: ['m'],
    bird_02: ['m'],
    bird_04: ['m'],
    bird_06: ['m'],
    bird_08: ['m'],
    bird_10: ['m'],
    bird_12: ['m'],
    bug_02: ['m'],
    bug_04: ['m'],
    bug_06: ['m'],
    bug_08: ['m'],
    bug_10: ['m'],
    bug_12: ['m'],
    japanese_02: ['m'],
    japanese_04: ['m'],
    japanese_06: ['m'],
    mystic_02: ['m'],
    mystic_04: ['m'],
    mystic_06: ['m'],
    mystic_08: ['m'],
    mystic_10: ['m'],
    mystic_12: ['m'],
    plant_02: ['m'],
    plant_04: ['m'],
    plant_06: ['m'],
    plant_08: ['m'],
    plant_10: ['m'],
    plant_12: ['m'],
    reptile_02: ['m'],
    reptile_04: ['m'],
    reptile_06: ['m'],
    reptile_08: ['m'],
    reptile_10: ['m'],
    reptile_12: ['m'],
  },
}
