export const AXIE_CLASSES = [
	'aqua',
	'beast',
	'bird',
	'bug',
	'mystic',
	'plant',
	'reptile',
	'japanese',
]
export const AXIE_BODY_SHAPES = [
	'bigyak',
	'curly',
	'furry',
	'normal',
	'spiky',
	'sumo',
	'wetdog',
] as const

export const AXIE_PARTS_MAP: Record<string, string> = {
	zeal: 'beast_02',
	'calico-zeal': 'beast_02',
	'little-peas': 'beast_04',
	snowflakes: 'beast_04',
	puppy: 'beast_10',
	chubby: 'beast_10',
	nyan: 'beast_02',
	'pointy-nyan': 'beast_02',
	coca: 'beast_02',
	'coca-shiny': 'beast_02',
	'nut-cracker': 'beast_02',
	'innocent-lamb': 'beast_06',
	'merry-lamb': 'beast_06',
	zen: 'beast_08',
	belieber: 'beast_12',
	ronin: 'beast_02',
	hasagi: 'beast_02',
	hero: 'beast_04',
	jaguar: 'beast_06',
	'risky-beast': 'beast_08',
	hamaya: 'beast_08',
	timber: 'beast_10',
	furball: 'beast_12',
	'beach-ball': 'beast_12',
	'beach-ball-shiny': 'beast_12',
	'little-branch': 'beast_02',
	'winter-branch': 'beast_02',
	imp: 'beast_04',
	kendama: 'beast_04',
	merry: 'beast_06',
	pocky: 'beast_08',
	umaibo: 'beast_08',
	'dual-blade': 'beast_10',
	arco: 'beast_12',
	cottontail: 'beast_02',
	'sakura-cottontail': 'beast_02',
	'cotton-candy': 'beast_02',
	'cotton-candy-shiny': 'beast_02',
	rice: 'beast_04',
	shiba: 'beast_06',
	hare: 'beast_08',
	gerbil: 'beast_12',
	'skull-cracker': 'beast_02',
	goda: 'beast_04',
	'axie-kiss': 'beast_08',
	confident: 'beast_10',
	mosquito: 'bug_02',
	'feasting-mosquito': 'bug_02',
	pincer: 'bug_04',
	'cute-bunny': 'bug_08',
	kawaii: 'bug_08',
	'square-teeth': 'bug_10',
	lagging: 'bug_02',
	laggingggggg: 'bug_02',
	antenna: 'bug_04',
	caterpillars: 'bug_06',
	pliers: 'bug_08',
	parasite: 'bug_10',
	p4r451t3: 'bug_10',
	'leaf-bug': 'bug_08',
	ant: 'bug_02',
	'fire-ant': 'bug_02',
	'twin-tail': 'bug_04',
	'fish-snack': 'bug_06',
	maki: 'bug_06',
	'gravel-ant': 'bug_08',
	pupae: 'bug_10',
	'thorny-caterpillar': 'bug_12',
	'snail-shell': 'bug_02',
	'starry-shell': 'bug_02',
	'garish-worm': 'bug_04',
	'candy-canes': 'bug_04',
	'buzz-buzz': 'bug_06',
	sandal: 'bug_08',
	scarab: 'bug_10',
	'spiky-wing': 'bug_12',
	larva: 'bug_02',
	vector: 'bug_02',
	'beetle-spike': 'bug_04',
	'ear-breathing': 'bug_06',
	tassels: 'bug_10',
	earwing: 'bug_12',
	mon: 'bug_12',
	bookworm: 'bug_02',
	'broken-bookworm': 'bug_02',
	neo: 'bug_04',
	'flower-sunglasses': 'bug_04',
	'flower-sunglasses-shiny': 'bug_04',
	nerdy: 'bug_08',
	kotaro: 'reptile_04',
	sleepless: 'aqua_02',
	insomnia: 'aqua_02',
	yen: 'aqua_02',
	clear: 'aqua_04',
	gero: 'aqua_08',
	telescope: 'aqua_10',
	lam: 'aqua_02',
	'lam-handsome': 'aqua_02',
	catfish: 'aqua_04',
	'risky-fish': 'aqua_08',
	'bubble-fish': 'aqua_08',
	'bubble-fish-shiny': 'aqua_08',
	piranha: 'aqua_10',
	geisha: 'aqua_10',
	babylonia: 'aqua_02',
	'candy-babylonia': 'aqua_02',
	'teal-shell': 'aqua_04',
	clamshell: 'aqua_06',
	anemone: 'aqua_10',
	oranda: 'aqua_10',
	'shoal-star': 'aqua_12',
	'5h04l-5t4r': 'aqua_12',
	nimo: 'aqua_04',
	'red-nimo': 'aqua_02',
	'tiny-fan': 'aqua_04',
	bubblemaker: 'aqua_06',
	inkling: 'aqua_08',
	gill: 'aqua_10',
	seaslug: 'aqua_12',
	koi: 'aqua_02',
	'kuro-koi': 'aqua_02',
	koinobori: 'aqua_02',
	tadpole: 'aqua_06',
	ranchu: 'aqua_08',
	navaga: 'aqua_10',
	shrimp: 'aqua_12',
	hermit: 'aqua_02',
	'crystal-hermit': 'aqua_02',
	'blue-moon': 'aqua_04',
	goldfish: 'aqua_06',
	sponge: 'aqua_08',
	perch: 'aqua_12',
	'pink-cheek': 'bird_02',
	'heart-cheek': 'bird_02',
	'early-bird': 'bird_04',
	owl: 'bird_06',
	'peace-maker': 'bird_04',
	curly: 'bird_10',
	'risky-bird': 'bird_12',
	karimata: 'bird_12',
	swallow: 'bird_02',
	'snowy-swallow': 'bird_02',
	'feather-fan': 'bird_04',
	'the-last-one': 'bird_06',
	cloud: 'bird_08',
	'granmas-fan': 'bird_10',
	omatsuri: 'bird_10',
	'post-fight': 'bird_12',
	balloon: 'bird_02',
	'starry-balloon': 'bird_02',
	cupid: 'bird_04',
	origami: 'bird_04',
	raven: 'bird_06',
	'pigeon-post': 'bird_08',
	kingfisher: 'bird_10',
	'tri-feather': 'bird_12',
	eggshell: 'bird_02',
	'golden-shell': 'bird_02',
	cuckoo: 'bird_04',
	trump: 'bird_06',
	kestrel: 'bird_08',
	'wing-horn': 'bird_10',
	'feather-spear': 'bird_12',
	'spruce-spear': 'bird_12',
	doubletalk: 'bird_02',
	'mr-doubletalk': 'bird_02',
	'hungry-bird': 'bird_08',
	'little-owl': 'bird_08',
	mavis: 'bird_02',
	'sky-mavis': 'bird_02',
	lucas: 'bird_04',
	'icy-gaze': 'bird_04',
	robin: 'bird_10',
	gecko: 'reptile_02',
	'crimson-gecko': 'reptile_02',
	tricky: 'reptile_04',
	scar: 'reptile_08',
	dokuganryu: 'reptile_08',
	topaz: 'reptile_10',
	kabuki: 'reptile_10',
	'toothless-bite': 'reptile_02',
	'venom-bite': 'reptile_02',
	'razor-bite': 'reptile_08',
	'tiny-turtle': 'reptile_10',
	dango: 'reptile_10',
	'tiny-carrot': 'reptile_10',
	pogona: 'reptile_02',
	'deadly-pogona': 'reptile_02',
	friezard: 'reptile_04',
	'curved-spine': 'reptile_06',
	'small-frill': 'reptile_08',
	swirl: 'reptile_10',
	sidebarb: 'reptile_12',
	'bone-sail': 'reptile_02',
	'rugged-sail': 'reptile_02',
	'tri-spikes': 'reptile_04',
	'green-thorns': 'reptile_06',
	'indian-star': 'reptile_08',
	'1nd14n-5t4r': 'reptile_08',
	'frozen-bucket': 'reptile_08',
	'red-ear': 'reptile_10',
	'turtle-buoy': 'reptile_10',
	'turtle-buoy-shiny': 'reptile_10',
	croc: 'reptile_12',
	'wall-gecko': 'reptile_02',
	'escaped-gecko': 'reptile_02',
	iguana: 'reptile_04',
	'tiny-dino': 'reptile_06',
	'fir-trunk': 'reptile_06',
	'snake-jar': 'reptile_08',
	'december-surprise': 'reptile_08',
	gila: 'reptile_10',
	'grass-snake': 'reptile_12',
	unko: 'reptile_02',
	'pinku-unko': 'reptile_02',
	'watermelon-ice-cream': 'reptile_02',
	'strawberry-ice-cream': 'reptile_02',
	'vanilla-ice-cream': 'reptile_02',
	'watermelon-ice-cream-shiny': 'reptile_02',
	'strawberry-ice-cream-shiny': 'reptile_02',
	'vanilla-ice-cream-shiny': 'reptile_02',
	'scaly-spear': 'reptile_04',
	cerastes: 'reptile_06',
	'scaly-spoon': 'reptile_08',
	incisor: 'reptile_10',
	bumpy: 'reptile_12',
	carrot: 'plant_02',
	'namek-carrot': 'plant_02',
	cattail: 'plant_04',
	hatsune: 'plant_06',
	yam: 'plant_08',
	'potato-leaf': 'plant_10',
	'hot-butt': 'plant_12',
	serious: 'plant_02',
	humorless: 'plant_02',
	zigzag: 'plant_04',
	rudolph: 'plant_04',
	herbivore: 'plant_08',
	'silence-whisper': 'plant_10',
	papi: 'plant_02',
	'dreamy-papi': 'plant_02',
	confused: 'plant_04',
	'cucumber-slice': 'plant_08',
	blossom: 'plant_10',
	leafy: 'plant_02',
	'the-last-leaf': 'plant_02',
	clover: 'plant_04',
	rosa: 'plant_06',
	sakura: 'plant_08',
	maiko: 'plant_08',
	hollow: 'plant_10',
	pinecones: 'plant_10',
	lotus: 'plant_12',
	turnip: 'plant_02',
	'pink-turnip': 'plant_02',
	shiitake: 'plant_04',
	yakitori: 'plant_04',
	bidens: 'plant_06',
	'watering-can': 'plant_08',
	mint: 'plant_10',
	pumpkin: 'plant_12',
	'bamboo-shoot': 'plant_02',
	'golden-bamboo-shoot': 'plant_02',
	beech: 'plant_04',
	yorishiro: 'plant_04',
	'rose-bud': 'plant_06',
	'strawberry-shortcake': 'plant_08',
	cactus: 'plant_10',
	'santas-gift': 'plant_10',
	watermelon: 'plant_12',
}

export const AXIE_COLORS_MAP: Record<string, string> = {
	'beast-00': '#fdfcf2',
	'beast-01': '#544f44',
	'beast-02': '#ffd500',
	'beast-03': '#fdb014',
	'beast-04': '#f5a037',
	'beast-06': '#427cad',
	'plant-00': '#fefdf1',
	'plant-01': '#4e523e',
	'plant-02': '#afdb1b',
	'plant-03': '#decd00',
	'plant-04': '#99ff73',
	'aquatic-00': '#f4fff4',
	'aquatic-01': '#4d545e',
	'aquatic-02': '#00f1d2',
	'aquatic-03': '#00dff3',
	'aquatic-04': '#00b8ff',
	'aquatic-06': '#e12f64',
	'bug-00': '#fffaf5',
	'bug-01': '#553b39',
	'bug-02': '#ff606c',
	'bug-03': '#ff433e',
	'bug-04': '#df2e54',
	'bird-00': '#fff7ff',
	'bird-01': '#583c44',
	'bird-02': '#ff99b0',
	'bird-03': '#ffafc1',
	'bird-04': '#ff78b4',
	'reptile-00': '#fff7ff',
	'reptile-01': '#5e436d',
	'reptile-02': '#c569cf',
	'reptile-03': '#9967fb',
	'reptile-04': '#f8bbff',
	'reptile-06': '#00c15f',
	'dawn-00': '#fcfbf2',
	'dawn-01': '#594026',
	'dawn-02': '#bbbaff',
	'dawn-03': '#ffff8d',
	'dawn-04': '#a5ffff',
	'dusk-00': '#f4fefb',
	'dusk-01': '#1d4d4f',
	'dusk-02': '#0097a0',
	'dusk-03': '#007181',
	'dusk-04': '#00aeb7',
	'mech-00': '#f6fbff',
	'mech-01': '#505050',
	'mech-02': '#ced5d7',
	'mech-03': '#ad6d3f',
	'mech-04': '#8c8e9e',
	'body-frosty': '#f3fefe',
	'beast-summer': '#fe9701',
	'plant-summer': '#67e92f',
	'aquatic-summer': '#00c5d0',
	'bug-summer': '#ff4363',
	'bird-summer': '#ff78bb',
	'reptile-summer': '#e173ff',
	'dawn-summer': '#ffda00',
	'mech-summer': '#c7d7e9',
	'dusk-summer': '#474b84',
}

export const PART_POSITION: Record<string, { [key: string]: Array<string> }> = {
	back: {
		aqua_02: ['m'],
		aqua_04: ['m'],
		aqua_06: ['m'],
		aqua_08: ['m'],
		aqua_10: ['m'],
		aqua_12: ['m'],
		beast_02: ['m'],
		beast_04: ['m'],
		beast_06: ['m'],
		beast_08: ['m'],
		beast_10: ['m'],
		beast_12: ['m'],
		bird_02: ['m'],
		bird_04: ['l', 'r'],
		bird_06: ['l', 'r'],
		bird_08: ['m'],
		bird_10: ['l', 'r'],
		bird_12: ['m'],
		bug_02: ['m'],
		bug_04: ['m'],
		bug_06: ['l', 'r'],
		bug_08: ['m'],
		bug_10: ['m'],
		bug_12: ['m'],
		japanese_02: ['l', 'r'],
		japanese_04: ['m'],
		japanese_06: ['m'],
		mystic_02: ['m'],
		mystic_04: ['m'],
		mystic_06: ['m'],
		mystic_08: ['m'],
		mystic_10: ['m'],
		mystic_12: ['m'],
		plant_02: ['m'],
		plant_06: ['m'],
		plant_04: ['m'],
		plant_08: ['m'],
		plant_10: ['m'],
		plant_12: ['m'],
		reptile_02: ['m'],
		reptile_04: ['m'],
		reptile_06: ['l', 'r'],
		reptile_08: ['m'],
		reptile_10: ['m'],
		reptile_12: ['l', 'r'],
	},
	ear: {
		aqua_02: ['l', 'r'],
		aqua_04: ['l', 'r'],
		aqua_06: ['l', 'r'],
		aqua_08: ['l', 'r'],
		aqua_10: ['l', 'r'],
		aqua_12: ['l', 'r'],
		beast_02: ['l', 'r'],
		beast_04: ['l', 'r'],
		beast_06: ['l', 'r'],
		beast_08: ['l', 'r'],
		beast_10: ['l', 'r'],
		beast_12: ['l', 'r'],
		bird_02: ['l', 'r'],
		bird_04: ['l', 'r'],
		bird_06: ['l', 'r'],
		bird_08: ['l', 'r'],
		bird_10: ['l', 'r'],
		bird_12: ['l', 'r'],
		bug_02: ['l', 'r'],
		bug_04: ['l', 'r'],
		bug_06: ['l', 'r'],
		bug_08: ['l', 'r'],
		bug_10: ['l', 'r'],
		bug_12: ['l', 'r'],
		japanese_02: ['l', 'r'],
		japanese_04: ['l', 'r'],
		japanese_06: ['l', 'r'],
		mystic_02: ['l', 'r'],
		mystic_04: ['l', 'r'],
		mystic_06: ['l', 'r'],
		mystic_08: ['l', 'r'],
		mystic_10: ['l', 'r'],
		mystic_12: ['l', 'r'],
		plant_02: ['l', 'r'],
		plant_04: ['l', 'r'],
		plant_06: ['l', 'r'],
		plant_08: ['l', 'r'],
		plant_10: ['l', 'r'],
		plant_12: ['l', 'r'],
		reptile_02: ['l', 'r'],
		reptile_04: ['l', 'r'],
		reptile_06: ['l', 'r'],
		reptile_08: ['l', 'r'],
		reptile_10: ['l', 'r'],
		reptile_12: ['l', 'r'],
	},
	eye: {
		aqua_02: ['m'],
		aqua_04: ['m'],
		aqua_06: ['m'],
		aqua_08: ['m'],
		aqua_10: ['m'],
		aqua_12: ['m'],
		beast_02: ['m'],
		beast_04: ['m'],
		beast_06: ['m'],
		beast_08: ['m'],
		beast_10: ['m'],
		beast_12: ['m'],
		bird_02: ['m'],
		bird_04: ['m'],
		bird_06: ['m'],
		bird_08: ['m'],
		bird_10: ['m'],
		bird_12: ['m'],
		bug_02: ['m'],
		bug_04: ['m'],
		bug_06: ['m'],
		bug_08: ['m'],
		bug_10: ['m'],
		bug_12: ['m'],
		mystic_02: ['m'],
		mystic_04: ['m'],
		mystic_06: ['m'],
		mystic_08: ['m'],
		mystic_10: ['m'],
		mystic_12: ['m'],
		plant_02: ['m'],
		plant_04: ['m'],
		plant_06: ['m'],
		plant_08: ['m'],
		plant_10: ['m'],
		plant_12: ['m'],
		reptile_02: ['m'],
		reptile_04: ['m'],
		reptile_06: ['m'],
		reptile_08: ['m'],
		reptile_10: ['m'],
		reptile_12: ['m'],
	},
	horn: {
		aqua_02: ['l', 'r'],
		aqua_04: ['t'],
		aqua_06: ['t'],
		aqua_08: ['t'],
		aqua_10: ['t'],
		aqua_12: ['t'],
		beast_02: ['l', 'r'],
		beast_04: ['l', 'r', 't'],
		beast_06: ['l', 'r'],
		beast_08: ['l', 'r'],
		beast_10: ['l', 'r'],
		beast_12: ['l', 'r'],
		bird_02: ['t'],
		bird_04: ['t'],
		bird_06: ['t'],
		bird_08: ['t'],
		bird_10: ['l', 'r'],
		bird_12: ['t'],
		bug_02: ['l', 'r'],
		bug_04: ['l', 'r'],
		bug_06: ['l', 'r'],
		bug_08: ['t'],
		bug_10: ['t'],
		bug_12: ['l', 'r'],
		japanese_02: ['t'],
		japanese_04: ['l', 'r'],
		japanese_06: ['t'],
		mystic_02: ['l', 'r'],
		mystic_04: ['l', 'r'],
		mystic_06: ['t'],
		mystic_08: ['t'],
		mystic_10: ['l', 'r'],
		mystic_12: ['t'],
		plant_02: ['t'],
		plant_04: ['t'],
		plant_06: ['t'],
		plant_08: ['t'],
		plant_10: ['t'],
		plant_12: ['t'],
		reptile_02: ['t'],
		reptile_04: ['t'],
		reptile_06: ['l', 'r'],
		reptile_08: ['l', 'r'],
		reptile_10: ['l', 'r'],
		reptile_12: ['l', 'r'],
	},
	tail: {
		aqua_02: ['m'],
		aqua_04: ['m'],
		aqua_06: ['m'],
		aqua_08: ['m'],
		aqua_10: ['m'],
		aqua_12: ['m'],
		beast_02: ['m'],
		beast_04: ['m'],
		beast_06: ['m'],
		beast_08: ['m'],
		beast_10: ['m'],
		beast_12: ['m'],
		bird_02: ['m'],
		bird_04: ['m'],
		bird_06: ['m'],
		bird_08: ['m'],
		bird_10: ['m'],
		bird_12: ['m'],
		bug_02: ['m'],
		bug_04: ['m'],
		bug_06: ['m'],
		bug_08: ['m'],
		bug_10: ['m'],
		bug_12: ['m'],
		japanese_02: ['m'],
		japanese_04: ['m'],
		japanese_06: ['m'],
		mystic_02: ['m'],
		mystic_04: ['m'],
		mystic_06: ['m'],
		mystic_08: ['m'],
		mystic_10: ['m'],
		mystic_12: ['m'],
		plant_02: ['m'],
		plant_04: ['m'],
		plant_06: ['m'],
		plant_08: ['m'],
		plant_10: ['m'],
		plant_12: ['m'],
		reptile_02: ['m'],
		reptile_04: ['m'],
		reptile_06: ['m'],
		reptile_08: ['m'],
		reptile_10: ['m'],
		reptile_12: ['m'],
	},
}
